# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build org`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t org`.

FROM node:hydrogen-alpine3.21 AS base


WORKDIR  /app
COPY package.json package-lock.json ./
RUN npm install




FROM base AS builder
WORKDIR /app
COPY .  .
RUN npm install
RUN npx nx build



FROM  node:hydrogen-alpine3.21 AS finalStage
WORKDIR /app
COPY  --from=builder /app/ .
RUN npx prisma generate --schema=packages/database/prisma/schema


EXPOSE 3030
CMD [ "npm", "start" ]




