name: "artificium"
services:
  artificium:
    build:
      context: .
    ports:
      - 3030:3030
    depends_on:
      - mongodb
    volumes:
      - ./packages:/app/packages
      - ./src:/app/src
  mongodb:
    image: mongodb/mongodb-atlas-local
    ports:
      - 27017:27017
    volumes:
      - mongo_vol:/app/mongodb
volumes:
  mongo_vol:
    driver: local